# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lB2F8EcgZzaF2KqOICRshpXL9oMsDTNmBj85giR9seXZKxVu+iNPAnf1s45uvoB1QW7EvSPe83vpU4kRruKmOTRIntkKHeusFJnFriGzJVxpK4fmdo2fdZ62q/NsCDfbzCGFQhaV8cC7T6b/HRqvRK1ORF88MBonfMHAgbNuwNzNUln2qRrEmMiZhipghbQlpSXEK8goLli+jFHa3fld59ZvVUlUeJ3m7x8YSZByqZxsBrtdPF9ufeVvuTf7Rt8htgP4EY3YHVSCqEk4s4SPEPRWCwDxH6rrT+6U3XP0LtuMZNLYMTLaWHH4DyehZ/fIELyUDNX6HtaJDQMaOunENLKg4NDPQmJ2mAUMPxnMdVnXSjbydYgYOtVIf7XzLpwWJZLTLlB/e4RZiJpJoE8kPEE+IgnfdILDSxt+URoeal+NmOLzkkVWOotqNyoobGZhqfnd267kVLyJ25AV04aCDdz/Q65mzGEqd+xd0cB8oRDM137cksZ14stQzsa6xa/IXb3b4rw+g1WxJssoKWB0b6K7Zf03lciVIlLU/GEsoIOmw5SBF/q0aEvdjZyIKwh/KkBKMBLHihijsnywM6cecQizZLTmb7+wQhnB97x5RbG87EgsIXd73mTJFjIeP0005uJN/LdFFdciu078eHD7+kJriGvuLCx/Su+1KjSk9Tg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
