travis:
  secure:
    BINSTAR_TOKEN: lB2F8EcgZzaF2KqOICRshpXL9oMsDTNmBj85giR9seXZKxVu+iNPAnf1s45uvoB1QW7EvSPe83vpU4kRruKmOTRIntkKHeusFJnFriGzJVxpK4fmdo2fdZ62q/NsCDfbzCGFQhaV8cC7T6b/HRqvRK1ORF88MBonfMHAgbNuwNzNUln2qRrEmMiZhipghbQlpSXEK8goLli+jFHa3fld59ZvVUlUeJ3m7x8YSZByqZxsBrtdPF9ufeVvuTf7Rt8htgP4EY3YHVSCqEk4s4SPEPRWCwDxH6rrT+6U3XP0LtuMZNLYMTLaWHH4DyehZ/fIELyUDNX6HtaJDQMaOunENLKg4NDPQmJ2mAUMPxnMdVnXSjbydYgYOtVIf7XzLpwWJZLTLlB/e4RZiJpJoE8kPEE+IgnfdILDSxt+URoeal+NmOLzkkVWOotqNyoobGZhqfnd267kVLyJ25AV04aCDdz/Q65mzGEqd+xd0cB8oRDM137cksZ14stQzsa6xa/IXb3b4rw+g1WxJssoKWB0b6K7Zf03lciVIlLU/GEsoIOmw5SBF/q0aEvdjZyIKwh/KkBKMBLHihijsnywM6cecQizZLTmb7+wQhnB97x5RbG87EgsIXd73mTJFjIeP0005uJN/LdFFdciu078eHD7+kJriGvuLCx/Su+1KjSk9Tg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
